//! Baked onboarding QR codes. One module per supported board, generated by
//! tools/generate_qr.py and gated by a same-named Cargo feature; exactly one
//! board feature is enabled at a time (see Cargo.toml).

#[cfg(feature = "board-x4")]
mod x4;

#[cfg(feature = "board-x4")]
pub use x4::*;

#[cfg(not(feature = "board-x4"))]
compile_error!("enable exactly one board-* feature, e.g. board-x4");
