//! Emits `ram-layout.x`, the linker fragment that pins the previous-frame
//! framebuffer to the top of `dram2_seg` and hands every byte below it to
//! the main stack. See `src/sync_mem.rs` for the ownership story and
//! `docs/plans/2026-07-06-x3-support-plan.md` for the stack budget.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Must equal `size_of::<display::fb::Framebuffer>()`: the repr(C) pixel
/// array plus the one-byte drawing-frame field. The ASSERT in the emitted
/// script fails the link if the display crate's layout drifts from this
/// copy.
fn prev_fb_bytes() -> usize {
    let pixels = if env::var_os("CARGO_FEATURE_DEVICE_X3").is_some() {
        792 / 8 * 528 // X3: 792x528 UC8253
    } else {
        800 / 8 * 480 // X4: 800x480 SSD1677
    };
    pixels + 1
}

/// Floor for `_stack_start - _stack_end`. The reader's deep path (zip
/// inflate + XHTML parse + pagination) peaked just under the 27,380-byte
/// stack the pre-esp-hal-1.x layout provided; anything less has already
/// shipped silent .bss corruption once.
const MIN_STACK_BYTES: usize = 27 * 1024;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let fb = prev_fb_bytes();

    let script = format!(
        r#"/* Generated by fw/build.rs - do not edit.

   dram2_seg (the boot-loader shadow above the DRAM region) holds only the
   previous-frame framebuffer, packed against the segment's top. The gap
   left underneath - which used to be the radio's dram2 heap share - is
   claimed by the main stack via the _stack_start overrides below. The
   radio's smaller heap is compensated at runtime in fw/src/tasks/wifi.rs. */

_prev_fb_slot = (ORIGIN(dram2_seg) + LENGTH(dram2_seg) - {fb}) & 0xFFFFFFFC;

SECTIONS {{
  .dram2_prev_fb _prev_fb_slot (NOLOAD) :
  {{
    KEEP(*(.dram2_prev_fb .dram2_prev_fb.*));
  }}
}}

/* Zero is allowed so bins that never touch sync_mem (test_dma) still link. */
ASSERT(SIZEOF(.dram2_prev_fb) == {fb} || SIZEOF(.dram2_prev_fb) == 0,
       ".dram2_prev_fb size differs from fw/build.rs prev_fb_bytes()");

/* Real assignments beat esp-hal stack.x's PROVIDEs. Boot SP, esp-rtos's
   main-task range check and the debug-assist watchpoint all follow these. */
_stack_start = _prev_fb_slot & 0xFFFFFFF0;
_stack_start_cpu0 = _stack_start;

ASSERT(_stack_start - _stack_end >= {min_stack},
       "main stack under the 27K reader budget; trim statics or rebalance dram2 (see fw/build.rs)");
"#,
        fb = fb,
        min_stack = MIN_STACK_BYTES,
    );

    fs::write(out_dir.join("ram-layout.x"), script).unwrap();
    println!("cargo:rustc-link-search={}", out_dir.display());

    // linkall.x is emitted here instead of .cargo/config.toml rustflags: cargo
    // merges that file with any ancestor checkout's copy (a worktree nested
    // inside the repo), and a doubled linker script fails the link with
    // "region 'ICACHE' already defined". A build script runs once per package,
    // so this cannot double. Skip it only when some config still supplies the
    // flag (a checkout from before this change acting as the ancestor). It
    // must precede ram-layout.x, which references linkall.x's dram2_seg.
    println!("cargo:rerun-if-env-changed=CARGO_ENCODED_RUSTFLAGS");
    let rustflags = env::var("CARGO_ENCODED_RUSTFLAGS").unwrap_or_default();
    if !rustflags.contains("-Tlinkall.x") {
        println!("cargo:rustc-link-arg-bins=-Tlinkall.x");
    }
    println!("cargo:rustc-link-arg-bins=-Tram-layout.x");
}
