#!/usr/bin/env python3
"""Bake the portal-URL QR code into ui/src/qr_generated.rs.

The portal's address is a compile-time constant, so its QR can be a
static table: run with `uv run --with qrcode tools/generate_qr.py`.

The hotspot join QR is NOT generated here: its WPA2 PSK is minted per
portal session on the device (fw/src/tasks/wifi.rs), so the join code
is encoded at render time by ui/src/join_qr.rs.
"""

from pathlib import Path

import qrcode

CODES = [
    ("QR_PORTAL", "http://192.168.4.1/"),
]

OUT = Path(__file__).resolve().parent.parent / "ui" / "src" / "qr_generated.rs"


def matrix_for(content: str):
    qr = qrcode.QRCode(
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=1,
        border=0,
    )
    qr.add_data(content)
    qr.make(fit=True)
    return qr.modules


def emit(name: str, content: str) -> str:
    modules = matrix_for(content)
    size = len(modules)
    stride = (size + 7) // 8
    rows = []
    for row in modules:
        packed = bytearray(stride)
        for x, dark in enumerate(row):
            if dark:
                packed[x // 8] |= 0x80 >> (x % 8)
        rows.append(", ".join(f"0x{byte:02x}" for byte in packed))
    bits = ",\n    ".join(rows)
    return (
        f"/// `{content}`\n"
        "#[rustfmt::skip]\n"
        f"pub const {name}_SIZE: usize = {size};\n"
        "#[rustfmt::skip]\n"
        f"pub const {name}_STRIDE: usize = {stride};\n"
        "#[rustfmt::skip]\n"
        f"pub const {name}_BITS: [u8; {size * stride}] = [\n    {bits},\n];\n"
    )


header = (
    "//! Generated by tools/generate_qr.py. Do not edit.\n"
    "//!\n"
    "//! The portal-URL QR code as packed 1-bit module rows (MSB first,\n"
    "//! 1 = dark module). The hotspot join QR is not here: its PSK is\n"
    "//! per-session, so ui/src/join_qr.rs encodes it at render time.\n\n"
)
OUT.write_text(header + "\n".join(emit(name, content) for name, content in CODES))
print(f"wrote {OUT}")
