#!/usr/bin/env python3
"""Bake a board's onboarding QR codes into ui/src/qr_generated/<board>.rs.

The portal's QR contents are compile-time constants (an open hotspot
join string and the portal URL), so the firmware never needs a QR
encoder: run with `uv run --with qrcode tools/generate_qr.py`.

Pass --board/--ssid for a board other than the X4, e.g.:
    uv run --with qrcode tools/generate_qr.py --board newboard --ssid NEWBOARD-SSID
"""

import argparse
from pathlib import Path

import qrcode

ROOT = Path(__file__).resolve().parent.parent


def matrix_for(content: str):
    qr = qrcode.QRCode(
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=1,
        border=0,
    )
    qr.add_data(content)
    qr.make(fit=True)
    return qr.modules


def emit(name: str, content: str) -> str:
    modules = matrix_for(content)
    size = len(modules)
    stride = (size + 7) // 8
    rows = []
    for row in modules:
        packed = bytearray(stride)
        for x, dark in enumerate(row):
            if dark:
                packed[x // 8] |= 0x80 >> (x % 8)
        rows.append(", ".join(f"0x{byte:02x}" for byte in packed))
    bits = ",\n    ".join(rows)
    return (
        f"/// `{content}`\n"
        f"pub const {name}_SIZE: usize = {size};\n"
        f"pub const {name}_STRIDE: usize = {stride};\n"
        f"pub const {name}_BITS: [u8; {size * stride}] = [\n    {bits},\n];\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--board", default="x4", help="board slug, e.g. x4")
    parser.add_argument("--ssid", default="XTEINK-X4", help="open-hotspot SSID to join")
    args = parser.parse_args()

    codes = [
        ("QR_JOIN", f"WIFI:T:nopass;S:{args.ssid};;"),
        ("QR_PORTAL", "http://192.168.4.1/"),
    ]
    out = ROOT / "ui" / "src" / "qr_generated" / f"{args.board}.rs"

    header = (
        f"//! Generated by `tools/generate_qr.py --board {args.board}`. Do not edit.\n"
        "//!\n"
        "//! Onboarding QR codes as packed 1-bit module rows (MSB first,\n"
        "//! 1 = dark module).\n\n"
    )
    out.write_text(header + "\n".join(emit(name, content) for name, content in codes))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
