#!/usr/bin/env python3
"""Rasterize the Merriweather reading faces for the display crate.

Emits display/src/merriweather_generated.rs: all three reading sizes (19,
22, 26px) in four styles each, behind the Font setting. Unlike Literata,
every Merriweather size lives in this one file — the family arrived after
the golden frames were pinned to Literata, so regenerating it never churns
goldens.

Merriweather (Sorkin Type, SIL Open Font License) is shipped as two variable
fonts; the four styles are instanced from them at the text optical size
(opsz 18), normal width, weights 400/700. Line heights and baselines match
the Literata set at each size so pagination advances stay family-independent.
The TTFs are downloaded on demand into tools/fonts/ (gitignored); only the
generated bitmaps are committed, which OFL permits.
"""
from pathlib import Path
from urllib.request import urlretrieve

from PIL import ImageFont

from fontgen_common import codepoints_from_ranges, kerning_entries, rasterize_glyph, write_kerning

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts" / "merriweather"
OUT = ROOT / "display" / "src" / "merriweather_generated.rs"

BASE = "https://github.com/google/fonts/raw/main/ofl/merriweather"
# (local file, remote file) for the two variable sources.
SOURCES = [
    ("Merriweather.ttf", "Merriweather%5Bopsz,wdth,wght%5D.ttf"),
    ("Merriweather-Italic.ttf", "Merriweather-Italic%5Bopsz,wdth,wght%5D.ttf"),
]

# (style const suffix, source file, variation axes [wght, wdth, opsz]).
# opsz 18 is the text/reading end of the optical-size axis; wdth 100 normal.
FONTS = [
    ("REGULAR", "Merriweather.ttf", [400, 100, 18]),
    ("ITALIC", "Merriweather-Italic.ttf", [400, 100, 18]),
    ("BOLD", "Merriweather.ttf", [700, 100, 18]),
    ("BOLD_ITALIC", "Merriweather-Italic.ttf", [700, 100, 18]),
]

# (px, line_height, baseline) — identical to the Literata sets so a family
# change never moves the line grid, only the glyphs on it.
SIZES = [
    (19, 26, 20),
    (22, 30, 23),
    (26, 36, 27),
]

# Same coverage as the Literata reading sets so a family change never swaps
# a rendered glyph for the '?' fallback.
RANGES = [
    (0x0020, 0x007E),  # Basic Latin
    (0x00A0, 0x024F),  # Latin-1, Latin Extended-A/B
    (0x0370, 0x03FF),  # Greek and Coptic
    (0x0400, 0x04FF),  # Cyrillic
    (0x1E00, 0x1EFF),  # Latin Extended Additional
    (0x2000, 0x206F),  # General Punctuation
    (0x20A0, 0x20CF),  # Currency Symbols
    (0x2100, 0x214F),  # Letterlike Symbols
    (0x2190, 0x21FF),  # Arrows
    (0x25A0, 0x25FF),  # Geometric Shapes
]


def codepoints():
    return codepoints_from_ranges(RANGES)


def ensure_fonts():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for local, remote in SOURCES:
        path = FONT_DIR / local
        if not path.exists():
            urlretrieve(f"{BASE}/{remote}", path)


def load_font(source, axes, px):
    font = ImageFont.truetype(str(FONT_DIR / source), px)
    font.set_variation_by_axes(axes)
    return font


def main():
    ensure_fonts()
    out = []
    out.append("// Generated by tools/generate_merriweather.py. Do not edit by hand.\n")
    out.append("use crate::font::{BitmapFont, GlyphMetric, KerningEntry};\n\n")
    cps = codepoints()
    out.append(f"#[rustfmt::skip]\npub const MERRIWEATHER_COUNT: usize = {len(cps)};\n")
    out.append("#[rustfmt::skip]\npub static MERRIWEATHER_CODEPOINTS: [u16; MERRIWEATHER_COUNT] = [\n")
    for chunk_start in range(0, len(cps), 12):
        chunk = cps[chunk_start : chunk_start + 12]
        out.append("    ")
        out.append(", ".join(f"0x{cp:04X}" for cp in chunk))
        out.append(",\n")
    out.append("];\n\n")

    for px, line_height, baseline in SIZES:
        for style, source, axes in FONTS:
            font = load_font(source, axes, px)
            metrics = []
            bitmap = []
            offset = 0
            for code in cps:
                width, height, x_offset, y_offset, advance, rows = rasterize_glyph(font, code)
                metrics.append((offset, len(rows), width, height, x_offset, y_offset, advance))
                bitmap.extend(rows)
                offset += len(rows)

            name = f"MERRIWEATHER_{px}_{style}"
            out.append(f"#[rustfmt::skip]\npub static {name}_METRICS: [GlyphMetric; MERRIWEATHER_COUNT] = [\n")
            for item in metrics:
                out.append(
                    "    GlyphMetric { "
                    f"offset: {item[0]}, len: {item[1]}, width: {item[2]}, height: {item[3]}, "
                    f"x_offset: {item[4]}, y_offset: {item[5]}, advance_fp: {item[6]} }},\n"
                )
            out.append("];\n\n")

            out.append(f"#[rustfmt::skip]\npub static {name}_BITMAP: [u8; {max(len(bitmap), 1)}] = [\n")
            if not bitmap:
                out.append("    0x00,\n")
            for chunk_start in range(0, len(bitmap), 16):
                chunk = bitmap[chunk_start : chunk_start + 16]
                out.append("    ")
                out.append(", ".join(f"0x{b:02X}" for b in chunk))
                out.append(",\n")
            out.append("];\n\n")

            write_kerning(out, name, kerning_entries(FONT_DIR / source, cps, px))

            out.append(f"#[rustfmt::skip]\npub static {name}: BitmapFont = BitmapFont {{\n")
            out.append("    codepoints: &MERRIWEATHER_CODEPOINTS,\n")
            out.append(f"    line_height: {line_height},\n")
            out.append(f"    baseline: {baseline},\n")
            out.append(f"    metrics: &{name}_METRICS,\n")
            out.append(f"    bitmap: &{name}_BITMAP,\n")
            out.append(f"    kerning: &{name}_KERNING,\n")
            out.append("};\n\n")

    OUT.write_text("".join(out))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
