#!/usr/bin/env python3
"""Rasterize extra Literata sizes for the host-side design mockup gallery.

Emits tools/preview/src/mockup_fonts_generated.rs. These sizes are mockup-only;
the firmware display crate keeps its single 22px set until a design direction
is chosen and the needed sizes are promoted into display/src.
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

from fontgen_common import ADVANCE_SCALE, THRESHOLD

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts" / "literata"
OUT = ROOT / "tools" / "preview" / "src" / "mockup_fonts_generated.rs"

# (size name, px, line_height, baseline, [(style name, ttf)])
SETS = [
    ("SMALL", 16, 22, 17, [
        ("REGULAR", "Literata-Regular.ttf"),
        ("BOLD", "Literata-Bold.ttf"),
        ("ITALIC", "Literata-Italic.ttf"),
    ]),
    ("TITLE", 30, 41, 31, [
        ("REGULAR", "Literata-Regular.ttf"),
        ("BOLD", "Literata-Bold.ttf"),
        ("ITALIC", "Literata-Italic.ttf"),
    ]),
    ("DISPLAY", 46, 62, 48, [
        ("REGULAR", "Literata-Regular.ttf"),
    ]),
]

RANGES = [
    (0x0020, 0x007E),  # Basic Latin
    (0x00A0, 0x00FF),  # Latin-1 Supplement
    (0x2010, 0x2026),  # dashes, curly quotes, bullet, ellipsis
    (0x2190, 0x2193),  # arrows
    (0x25A0, 0x25CF),  # geometric shapes
]


def codepoints():
    values = []
    for start, end in RANGES:
        values.extend(range(start, end + 1))
    return sorted(set(values))


def glyph(font, code):
    ch = chr(code)
    bbox = font.getbbox(ch, anchor="ls")
    advance = max(int(round(font.getlength(ch) * ADVANCE_SCALE)), ADVANCE_SCALE)
    if bbox is None:
        return (0, 0, 0, 0, max(advance, 1), [])
    left, top, right, bottom = bbox
    width = max(0, right - left)
    height = max(0, bottom - top)
    if width == 0 or height == 0:
        return (0, 0, left, top, max(advance, 1), [])
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    draw.text((-left, -top), ch, font=font, fill=255, anchor="ls")
    rows = []
    for y in range(height):
        byte = 0
        bits = 0
        for x in range(width):
            if image.getpixel((x, y)) >= THRESHOLD:
                byte |= 0x80 >> bits
            bits += 1
            if bits == 8:
                rows.append(byte)
                byte = 0
                bits = 0
        if bits:
            rows.append(byte)
    return (width, height, left, top, max(advance, 1), rows)


def main():
    out = []
    out.append("// Generated by tools/generate_mockup_fonts.py. Do not edit by hand.\n")
    out.append("#![allow(dead_code)]\n")
    out.append("use display::font::{BitmapFont, GlyphMetric, KerningEntry};\n\n")
    out.append("#[rustfmt::skip]\npub static MOCKUP_EMPTY_KERNING: [KerningEntry; 0] = [];\n\n")
    cps = codepoints()
    out.append(f"#[rustfmt::skip]\npub const MOCKUP_COUNT: usize = {len(cps)};\n")
    out.append("#[rustfmt::skip]\npub static MOCKUP_CODEPOINTS: [u16; MOCKUP_COUNT] = [\n")
    for chunk_start in range(0, len(cps), 12):
        chunk = cps[chunk_start : chunk_start + 12]
        out.append("    ")
        out.append(", ".join(f"0x{cp:04X}" for cp in chunk))
        out.append(",\n")
    out.append("];\n\n")

    for size_name, px, line_height, baseline, styles in SETS:
        for style, filename in styles:
            font = ImageFont.truetype(str(FONT_DIR / filename), px)
            metrics = []
            bitmap = []
            offset = 0
            for code in cps:
                width, height, x_offset, y_offset, advance, rows = glyph(font, code)
                metrics.append((offset, len(rows), width, height, x_offset, y_offset, advance))
                bitmap.extend(rows)
                offset += len(rows)

            name = f"{size_name}_{style}"
            out.append(f"#[rustfmt::skip]\npub static {name}_METRICS: [GlyphMetric; MOCKUP_COUNT] = [\n")
            for item in metrics:
                out.append(
                    "    GlyphMetric { "
                    f"offset: {item[0]}, len: {item[1]}, width: {item[2]}, height: {item[3]}, "
                    f"x_offset: {item[4]}, y_offset: {item[5]}, advance_fp: {item[6]} }},\n"
                )
            out.append("];\n\n")

            out.append(f"#[rustfmt::skip]\npub static {name}_BITMAP: [u8; {max(len(bitmap), 1)}] = [\n")
            if not bitmap:
                out.append("    0x00,\n")
            for chunk_start in range(0, len(bitmap), 16):
                chunk = bitmap[chunk_start : chunk_start + 16]
                out.append("    ")
                out.append(", ".join(f"0x{b:02X}" for b in chunk))
                out.append(",\n")
            out.append("];\n\n")

            out.append(f"#[rustfmt::skip]\npub static {name}: BitmapFont = BitmapFont {{\n")
            out.append("    codepoints: &MOCKUP_CODEPOINTS,\n")
            out.append(f"    line_height: {line_height},\n")
            out.append(f"    baseline: {baseline},\n")
            out.append(f"    metrics: &{name}_METRICS,\n")
            out.append(f"    bitmap: &{name}_BITMAP,\n")
            out.append("    kerning: &MOCKUP_EMPTY_KERNING,\n")
            out.append("};\n\n")

    OUT.write_text("".join(out))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
