#!/usr/bin/env python3
from pathlib import Path
from urllib.request import urlretrieve

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts" / "literata"
OUT = ROOT / "display" / "src" / "literata_generated.rs"

BASE = "https://raw.githubusercontent.com/googlefonts/literata/main/fonts/ttf"
FONTS = [
    ("REGULAR", "Literata-Regular.ttf"),
    ("ITALIC", "Literata-Italic.ttf"),
    ("BOLD", "Literata-Bold.ttf"),
    ("BOLD_ITALIC", "Literata-BoldItalic.ttf"),
]

RANGES = [
    (0x0020, 0x007E),  # Basic Latin
    (0x00A0, 0x024F),  # Latin-1, Latin Extended-A/B
    (0x0370, 0x03FF),  # Greek and Coptic
    (0x0400, 0x04FF),  # Cyrillic
    (0x1E00, 0x1EFF),  # Latin Extended Additional
    (0x2000, 0x206F),  # General Punctuation
    (0x20A0, 0x20CF),  # Currency Symbols
    (0x2100, 0x214F),  # Letterlike Symbols
    (0x2190, 0x21FF),  # Arrows
    (0x25A0, 0x25FF),  # Geometric Shapes
]
PX = 22
LINE_HEIGHT = 30
BASELINE = 23


def codepoints():
    values = []
    for start, end in RANGES:
        values.extend(range(start, end + 1))
    return sorted(set(values))


def ensure_fonts():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for _, name in FONTS:
        path = FONT_DIR / name
        if not path.exists():
            urlretrieve(f"{BASE}/{name}", path)


def glyph(font, code):
    ch = chr(code)
    bbox = font.getbbox(ch, anchor="ls")
    advance = int(round(font.getlength(ch)))
    if bbox is None:
        return (0, 0, 0, 0, max(advance, 1), [])
    left, top, right, bottom = bbox
    width = max(0, right - left)
    height = max(0, bottom - top)
    if width == 0 or height == 0:
        return (0, 0, left, top, max(advance, 1), [])
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    draw.text((-left, -top), ch, font=font, fill=255, anchor="ls")
    rows = []
    for y in range(height):
        byte = 0
        bits = 0
        for x in range(width):
            if image.getpixel((x, y)) >= 128:
                byte |= 0x80 >> bits
            bits += 1
            if bits == 8:
                rows.append(byte)
                byte = 0
                bits = 0
        if bits:
            rows.append(byte)
    return (width, height, left, top, max(advance, 1), rows)


def main():
    ensure_fonts()
    out = []
    out.append("// Generated by tools/generate_literata.py. Do not edit by hand.\n")
    out.append("use crate::font::{BitmapFont, GlyphMetric};\n\n")
    cps = codepoints()
    out.append(f"pub const LITERATA_COUNT: usize = {len(cps)};\n")
    out.append("pub static LITERATA_CODEPOINTS: [u16; LITERATA_COUNT] = [\n")
    for chunk_start in range(0, len(cps), 12):
        chunk = cps[chunk_start : chunk_start + 12]
        out.append("    ")
        out.append(", ".join(f"0x{cp:04X}" for cp in chunk))
        out.append(",\n")
    out.append("];\n\n")

    font_consts = []
    for style, filename in FONTS:
        font = ImageFont.truetype(str(FONT_DIR / filename), PX)
        metrics = []
        bitmap = []
        offset = 0
        for code in cps:
            width, height, x_offset, y_offset, advance, rows = glyph(font, code)
            metrics.append((offset, len(rows), width, height, x_offset, y_offset, advance))
            bitmap.extend(rows)
            offset += len(rows)

        out.append(f"pub static LITERATA_{style}_METRICS: [GlyphMetric; LITERATA_COUNT] = [\n")
        for item in metrics:
            out.append(
                "    GlyphMetric { "
                f"offset: {item[0]}, len: {item[1]}, width: {item[2]}, height: {item[3]}, "
                f"x_offset: {item[4]}, y_offset: {item[5]}, advance: {item[6]} }},\n"
            )
        out.append("];\n\n")

        out.append(f"pub static LITERATA_{style}_BITMAP: [u8; {len(bitmap)}] = [\n")
        for chunk_start in range(0, len(bitmap), 16):
            chunk = bitmap[chunk_start : chunk_start + 16]
            out.append("    ")
            out.append(", ".join(f"0x{b:02X}" for b in chunk))
            out.append(",\n")
        out.append("];\n\n")

        const_name = f"LITERATA_{style}"
        font_consts.append(const_name)
        out.append(f"pub static {const_name}: BitmapFont = BitmapFont {{\n")
        out.append("    codepoints: &LITERATA_CODEPOINTS,\n")
        out.append(f"    line_height: {LINE_HEIGHT},\n")
        out.append(f"    baseline: {BASELINE},\n")
        out.append(f"    metrics: &LITERATA_{style}_METRICS,\n")
        out.append(f"    bitmap: &LITERATA_{style}_BITMAP,\n")
        out.append("};\n\n")

    OUT.write_text("".join(out))


if __name__ == "__main__":
    main()
