#!/usr/bin/env python3
"""Rasterize the SemiBold reading faces for the Type Weight "Heavier" option.

Emits display/src/literata_semibold_generated.rs: Literata SemiBold (600) and
SemiBold Italic at the three reading sizes (19/22/26px), matching the
line_height/baseline of the Regular sets so a weight change is vertically
interchangeable at a given size. Heavy mode maps Regular->SemiBold and
Italic->SemiBoldItalic; Bold emphasis keeps the existing Bold (700) set, which
stays a step heavier so emphasis remains visible.

Like the other generators, the default Regular sets are deliberately not
touched here: glyph rasterization differs across Pillow/freetype builds, so
this file is a frozen artifact -- generate once, check in, do not re-run
casually or it churns the Heavy-mode goldens.
"""
from pathlib import Path
from urllib.request import urlretrieve

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts" / "literata"
OUT = ROOT / "display" / "src" / "literata_semibold_generated.rs"

BASE = "https://raw.githubusercontent.com/googlefonts/literata/main/fonts/ttf"
FONTS = [
    ("SEMIBOLD", "Literata-SemiBold.ttf"),
    ("SEMIBOLD_ITALIC", "Literata-SemiBoldItalic.ttf"),
]

# (px, line_height, baseline) -- identical to the Regular sets so Heavy and
# Normal share one vertical grid: 19 from generate_literata_sizes.py, 22 from
# generate_literata.py, 26 from generate_literata_sizes.py.
SIZES = [
    (19, 26, 20),
    (22, 30, 23),
    (26, 36, 27),
]

# Same coverage as the Regular reading sets so a weight change never swaps a
# rendered glyph for the '?' fallback.
RANGES = [
    (0x0020, 0x007E),  # Basic Latin
    (0x00A0, 0x024F),  # Latin-1, Latin Extended-A/B
    (0x0370, 0x03FF),  # Greek and Coptic
    (0x0400, 0x04FF),  # Cyrillic
    (0x1E00, 0x1EFF),  # Latin Extended Additional
    (0x2000, 0x206F),  # General Punctuation
    (0x20A0, 0x20CF),  # Currency Symbols
    (0x2100, 0x214F),  # Letterlike Symbols
    (0x2190, 0x21FF),  # Arrows
    (0x25A0, 0x25FF),  # Geometric Shapes
]


def codepoints():
    values = []
    for start, end in RANGES:
        values.extend(range(start, end + 1))
    return sorted(set(values))


def ensure_fonts():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for _, name in FONTS:
        path = FONT_DIR / name
        if not path.exists():
            urlretrieve(f"{BASE}/{name}", path)


def glyph(font, code):
    ch = chr(code)
    bbox = font.getbbox(ch, anchor="ls")
    advance = int(round(font.getlength(ch)))
    if bbox is None:
        return (0, 0, 0, 0, max(advance, 1), [])
    left, top, right, bottom = bbox
    width = max(0, right - left)
    height = max(0, bottom - top)
    if width == 0 or height == 0:
        return (0, 0, left, top, max(advance, 1), [])
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    draw.text((-left, -top), ch, font=font, fill=255, anchor="ls")
    rows = []
    for y in range(height):
        byte = 0
        bits = 0
        for x in range(width):
            if image.getpixel((x, y)) >= 128:
                byte |= 0x80 >> bits
            bits += 1
            if bits == 8:
                rows.append(byte)
                byte = 0
                bits = 0
        if bits:
            rows.append(byte)
    return (width, height, left, top, max(advance, 1), rows)


def main():
    ensure_fonts()
    out = []
    out.append("// Generated by tools/generate_literata_semibold.py. Do not edit by hand.\n")
    out.append("use crate::font::{BitmapFont, GlyphMetric};\n\n")
    cps = codepoints()
    out.append(f"pub const SEMIBOLD_COUNT: usize = {len(cps)};\n")
    out.append("pub static SEMIBOLD_CODEPOINTS: [u16; SEMIBOLD_COUNT] = [\n")
    for chunk_start in range(0, len(cps), 12):
        chunk = cps[chunk_start : chunk_start + 12]
        out.append("    ")
        out.append(", ".join(f"0x{cp:04X}" for cp in chunk))
        out.append(",\n")
    out.append("];\n\n")

    for px, line_height, baseline in SIZES:
        for style, filename in FONTS:
            font = ImageFont.truetype(str(FONT_DIR / filename), px)
            metrics = []
            bitmap = []
            offset = 0
            for code in cps:
                width, height, x_offset, y_offset, advance, rows = glyph(font, code)
                metrics.append((offset, len(rows), width, height, x_offset, y_offset, advance))
                bitmap.extend(rows)
                offset += len(rows)

            name = f"LITERATA_{px}_{style}"
            out.append(f"pub static {name}_METRICS: [GlyphMetric; SEMIBOLD_COUNT] = [\n")
            for item in metrics:
                out.append(
                    "    GlyphMetric { "
                    f"offset: {item[0]}, len: {item[1]}, width: {item[2]}, height: {item[3]}, "
                    f"x_offset: {item[4]}, y_offset: {item[5]}, advance: {item[6]} }},\n"
                )
            out.append("];\n\n")

            out.append(f"pub static {name}_BITMAP: [u8; {max(len(bitmap), 1)}] = [\n")
            if not bitmap:
                out.append("    0x00,\n")
            for chunk_start in range(0, len(bitmap), 16):
                chunk = bitmap[chunk_start : chunk_start + 16]
                out.append("    ")
                out.append(", ".join(f"0x{b:02X}" for b in chunk))
                out.append(",\n")
            out.append("];\n\n")

            out.append(f"pub static {name}: BitmapFont = BitmapFont {{\n")
            out.append("    codepoints: &SEMIBOLD_CODEPOINTS,\n")
            out.append(f"    line_height: {line_height},\n")
            out.append(f"    baseline: {baseline},\n")
            out.append(f"    metrics: &{name}_METRICS,\n")
            out.append(f"    bitmap: &{name}_BITMAP,\n")
            out.append("};\n\n")

    OUT.write_text("".join(out))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
