#!/usr/bin/env python3
"""Rasterize the Imprint UI Literata sizes for the firmware display crate.

Emits display/src/literata_extra_generated.rs: a 16px apparatus set
(regular/bold/italic) and a 46px display set (regular). The 22px reading
set stays in literata_generated.rs via tools/generate_literata.py.
"""
from pathlib import Path

from PIL import ImageFont

from fontgen_common import codepoints_from_ranges, kerning_entries, rasterize_glyph, write_kerning

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts" / "literata"
OUT = ROOT / "display" / "src" / "literata_extra_generated.rs"

# (size name, px, line_height, baseline, [(style name, ttf)])
SETS = [
    ("SMALL", 16, 22, 17, [
        ("REGULAR", "Literata-Regular.ttf"),
        ("BOLD", "Literata-Bold.ttf"),
        ("ITALIC", "Literata-Italic.ttf"),
    ]),
    ("DISPLAY", 46, 62, 48, [
        ("REGULAR", "Literata-Regular.ttf"),
    ]),
]

RANGES = [
    (0x0020, 0x007E),  # Basic Latin
    (0x00A0, 0x00FF),  # Latin-1 Supplement
    (0x2010, 0x2026),  # dashes, curly quotes, bullet, ellipsis
    (0x2190, 0x2193),  # arrows
]


def codepoints():
    return codepoints_from_ranges(RANGES)


def main():
    out = []
    out.append("// Generated by tools/generate_literata_extra.py. Do not edit by hand.\n")
    out.append("use crate::font::{BitmapFont, GlyphMetric, KerningEntry};\n\n")
    cps = codepoints()
    out.append(f"#[rustfmt::skip]\npub const EXTRA_COUNT: usize = {len(cps)};\n")
    out.append("#[rustfmt::skip]\npub static EXTRA_CODEPOINTS: [u16; EXTRA_COUNT] = [\n")
    for chunk_start in range(0, len(cps), 12):
        chunk = cps[chunk_start : chunk_start + 12]
        out.append("    ")
        out.append(", ".join(f"0x{cp:04X}" for cp in chunk))
        out.append(",\n")
    out.append("];\n\n")

    for size_name, px, line_height, baseline, styles in SETS:
        for style, filename in styles:
            font = ImageFont.truetype(str(FONT_DIR / filename), px)
            metrics = []
            bitmap = []
            offset = 0
            for code in cps:
                width, height, x_offset, y_offset, advance, rows = rasterize_glyph(font, code)
                metrics.append((offset, len(rows), width, height, x_offset, y_offset, advance))
                bitmap.extend(rows)
                offset += len(rows)

            name = f"LITERATA_{size_name}_{style}"
            out.append(f"#[rustfmt::skip]\npub static {name}_METRICS: [GlyphMetric; EXTRA_COUNT] = [\n")
            for item in metrics:
                out.append(
                    "    GlyphMetric { "
                    f"offset: {item[0]}, len: {item[1]}, width: {item[2]}, height: {item[3]}, "
                    f"x_offset: {item[4]}, y_offset: {item[5]}, advance_fp: {item[6]} }},\n"
                )
            out.append("];\n\n")

            out.append(f"#[rustfmt::skip]\npub static {name}_BITMAP: [u8; {max(len(bitmap), 1)}] = [\n")
            if not bitmap:
                out.append("    0x00,\n")
            for chunk_start in range(0, len(bitmap), 16):
                chunk = bitmap[chunk_start : chunk_start + 16]
                out.append("    ")
                out.append(", ".join(f"0x{b:02X}" for b in chunk))
                out.append(",\n")
            out.append("];\n\n")

            write_kerning(out, name, kerning_entries(FONT_DIR / filename, cps, px))

            out.append(f"#[rustfmt::skip]\npub static {name}: BitmapFont = BitmapFont {{\n")
            out.append("    codepoints: &EXTRA_CODEPOINTS,\n")
            out.append(f"    line_height: {line_height},\n")
            out.append(f"    baseline: {baseline},\n")
            out.append(f"    metrics: &{name}_METRICS,\n")
            out.append(f"    bitmap: &{name}_BITMAP,\n")
            out.append(f"    kerning: &{name}_KERNING,\n")
            out.append("};\n\n")

    OUT.write_text("".join(out))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
