#!/usr/bin/env python3
"""Rasterize the non-default Literata reading sizes for the display crate.

Emits display/src/literata_sizes_generated.rs: the 19px and 26px reading
sets (4 styles each) behind the Type Size setting. The default 22px set
stays in literata_generated.rs via tools/generate_literata.py — that file
is deliberately not regenerated here because glyph rasterization differs
across Pillow/freetype builds and regenerating it would churn every
checked-in golden frame that uses the default size.
"""
from pathlib import Path

from PIL import ImageFont

from fontgen_common import codepoints_from_ranges, kerning_entries, rasterize_glyph, write_kerning

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts" / "literata"
OUT = ROOT / "display" / "src" / "literata_sizes_generated.rs"

FONTS = [
    ("REGULAR", "Literata-Regular.ttf"),
    ("ITALIC", "Literata-Italic.ttf"),
    ("BOLD", "Literata-Bold.ttf"),
    ("BOLD_ITALIC", "Literata-BoldItalic.ttf"),
]

# (px, line_height, baseline) — keep ratios close to the 22px set's 30/23.
SIZES = [
    (19, 26, 20),
    (26, 36, 27),
]

# Same coverage as the 22px reading set so a size change never swaps a
# rendered glyph for the '?' fallback.
RANGES = [
    (0x0020, 0x007E),  # Basic Latin
    (0x00A0, 0x024F),  # Latin-1, Latin Extended-A/B
    (0x0370, 0x03FF),  # Greek and Coptic
    (0x0400, 0x04FF),  # Cyrillic
    (0x1E00, 0x1EFF),  # Latin Extended Additional
    (0x2000, 0x206F),  # General Punctuation
    (0x20A0, 0x20CF),  # Currency Symbols
    (0x2100, 0x214F),  # Letterlike Symbols
    (0x2190, 0x21FF),  # Arrows
    (0x25A0, 0x25FF),  # Geometric Shapes
]


def codepoints():
    return codepoints_from_ranges(RANGES)


def main():
    out = []
    out.append("// Generated by tools/generate_literata_sizes.py. Do not edit by hand.\n")
    out.append("use crate::font::{BitmapFont, GlyphMetric, KerningEntry};\n\n")
    cps = codepoints()
    out.append(f"#[rustfmt::skip]\npub const SIZES_COUNT: usize = {len(cps)};\n")
    out.append("#[rustfmt::skip]\npub static SIZES_CODEPOINTS: [u16; SIZES_COUNT] = [\n")
    for chunk_start in range(0, len(cps), 12):
        chunk = cps[chunk_start : chunk_start + 12]
        out.append("    ")
        out.append(", ".join(f"0x{cp:04X}" for cp in chunk))
        out.append(",\n")
    out.append("];\n\n")

    for px, line_height, baseline in SIZES:
        for style, filename in FONTS:
            font = ImageFont.truetype(str(FONT_DIR / filename), px)
            metrics = []
            bitmap = []
            offset = 0
            for code in cps:
                width, height, x_offset, y_offset, advance, rows = rasterize_glyph(font, code)
                metrics.append((offset, len(rows), width, height, x_offset, y_offset, advance))
                bitmap.extend(rows)
                offset += len(rows)

            name = f"LITERATA_{px}_{style}"
            out.append(f"#[rustfmt::skip]\npub static {name}_METRICS: [GlyphMetric; SIZES_COUNT] = [\n")
            for item in metrics:
                out.append(
                    "    GlyphMetric { "
                    f"offset: {item[0]}, len: {item[1]}, width: {item[2]}, height: {item[3]}, "
                    f"x_offset: {item[4]}, y_offset: {item[5]}, advance_fp: {item[6]} }},\n"
                )
            out.append("];\n\n")

            out.append(f"#[rustfmt::skip]\npub static {name}_BITMAP: [u8; {max(len(bitmap), 1)}] = [\n")
            if not bitmap:
                out.append("    0x00,\n")
            for chunk_start in range(0, len(bitmap), 16):
                chunk = bitmap[chunk_start : chunk_start + 16]
                out.append("    ")
                out.append(", ".join(f"0x{b:02X}" for b in chunk))
                out.append(",\n")
            out.append("];\n\n")

            write_kerning(out, name, kerning_entries(FONT_DIR / filename, cps, px))

            out.append(f"#[rustfmt::skip]\npub static {name}: BitmapFont = BitmapFont {{\n")
            out.append("    codepoints: &SIZES_CODEPOINTS,\n")
            out.append(f"    line_height: {line_height},\n")
            out.append(f"    baseline: {baseline},\n")
            out.append(f"    metrics: &{name}_METRICS,\n")
            out.append(f"    bitmap: &{name}_BITMAP,\n")
            out.append(f"    kerning: &{name}_KERNING,\n")
            out.append("};\n\n")

    OUT.write_text("".join(out))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
